export const SET_ENERGY_STRENGTH = 'SET_ENERGY_STRENGTH';
export const SET_EDITING_ENERGY_ID = 'SET_EDITING_ENERGY_ID';
export const SET_ENERGY_IS_MUTED = 'SET_ENERGY_IS_MUTED';
export const MOVE_ENERGY = 'MOVE_ENERGY';
export const DELETE_ENERGY = 'DELETE_ENERGY';
export const ADD_ENERGY = 'ADD_ENERGY';

export const SET_STATE = 'SET_STATE';
export const START_DRAGGING = 'START_DRAGGING';
export const STOP_DRAGGING = 'STOP_DRAGGING';
export const SET_PRESENTATION = 'SET_PRESENTATION';
